/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.home;

import com.acceuil.acceuilframe;
import java.awt.Toolkit;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import com.home.Homeframe;

/**
 *
 * @author Administrateur
 */
public class Homeframe1 extends javax.swing.JFrame {

    /**
     * Creates new form homeFrame
     */
    public Homeframe1() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("ic.png")));
        loadTable1();
    }
    
    public void loadAllDattaIntoTable1(List<Homebean1> list){
        DefaultTableModel dtn = (DefaultTableModel) jTable1.getModel();
        dtn.setRowCount(0);
        
        for(Homebean1 bean : list){
            Vector v = new Vector();
            v.add(bean.getId());
            v.add(bean.getNom_prof());
            v.add(bean.getCours());
            v.add(bean.getSalle());
            v.add(bean.getJour());
            v.add(bean.getMetier());
            v.add(bean.getFiliere());
            v.add(bean.getPromo());
            
            dtn.addRow(v);
        }
    }
    
    public void loadTable1(){
    Homebal bal = new Homebal();
    List list = bal.LoadData1();
    loadAllDattaIntoTable1(list);
}
    public void clearTextFieldData(){
        jTextFieldnom_p.setText("");
        jTextFielddate.setText("");
        jTextFieldmetier1.setText("");
        jTextFieldpromo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFielddate = new javax.swing.JTextField();
        jTextFieldnom_p = new javax.swing.JTextField();
        jTextFieldmetier1 = new javax.swing.JTextField();
        jComboBoxsalle = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButtonm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtoni = new javax.swing.JButton();
        jButtone = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldpromo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtons = new javax.swing.JButton();
        jTextFieldfiliere1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextFieldcours = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/login/logo-isep-diamniadio.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Imprimer");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Gestionaire Scolaire");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setText("Tableau Cours");

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Print");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 607, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(114, 114, 114)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(290, 290, 290)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(881, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 100));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1480, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 690, 1480, 100));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 204, 204)), "Données", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Salle :");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 90, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("nom_Prof:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Date:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 90, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Cours:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 20));

        jTextFielddate.setToolTipText("exemple: Lo");
        jPanel4.add(jTextFielddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 120, 30));

        jTextFieldnom_p.setToolTipText("exemple: Ibrahima");
        jPanel4.add(jTextFieldnom_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 200, 40));

        jTextFieldmetier1.setToolTipText("exemple: TIC");
        jPanel4.add(jTextFieldmetier1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, 30));

        jComboBoxsalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Amphitéatre", "Atelier", "C101", "C102", "C103", "C104", "C110", "C111", "C112", "C113", "C114", "C201", "C202", "C203", "C204", "C210", "C211", "C212", "C213", "C214", "C301", "C302", "C303", "C304", "C310", "C311", "C312", "C313", "C314", " " }));
        jComboBoxsalle.setToolTipText("");
        jComboBoxsalle.setAutoscrolls(true);
        jComboBoxsalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxsalleActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBoxsalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 100, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 204));
        jLabel10.setText("Filiére:");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 90, 20));

        jButtonm.setBackground(new java.awt.Color(51, 51, 255));
        jButtonm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonm.setText("Metre a jour");
        jButtonm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 153, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Etudiant");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 80, 70));

        jButtoni.setBackground(new java.awt.Color(51, 255, 51));
        jButtoni.setForeground(new java.awt.Color(255, 255, 255));
        jButtoni.setText("Inscrire");
        jButtoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoniActionPerformed(evt);
            }
        });
        jPanel4.add(jButtoni, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 100, 40));

        jButtone.setBackground(new java.awt.Color(0, 0, 0));
        jButtone.setForeground(new java.awt.Color(255, 255, 255));
        jButtone.setText("Enlever");
        jButtone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoneActionPerformed(evt);
            }
        });
        jPanel4.add(jButtone, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 100, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 204, 204));
        jLabel14.setText("Métier:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, 20));

        jTextFieldpromo.setToolTipText("exemple: DBE");
        jPanel4.add(jTextFieldpromo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 200, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 204));
        jLabel16.setText("Promo:");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 20));

        jButtons.setBackground(new java.awt.Color(255, 0, 0));
        jButtons.setForeground(new java.awt.Color(255, 255, 255));
        jButtons.setText("Supprimer");
        jButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsActionPerformed(evt);
            }
        });
        jPanel4.add(jButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 100, 40));

        jTextFieldfiliere1.setToolTipText("exemple: DBE");
        jPanel4.add(jTextFieldfiliere1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 30));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setText("Deconnexion");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 100, 30));

        jTextFieldcours.setToolTipText("exemple: Lo");
        jPanel4.add(jTextFieldcours, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 240, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 650, 560));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom_prof", "cours", "salle", "jour", "metier", "filiere", "promo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 650, 560));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 790));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxsalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxsalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxsalleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoniActionPerformed
        // TODO add your handling code here:
        String nom_prof = jTextFieldnom_p.getText();
        String cours = jTextFieldcours.getText();
        String salle = (String)jComboBoxsalle.getSelectedItem();
        String jour = jTextFielddate.getText();
        String metier = jTextFieldmetier1.getText();
        String filiere = jTextFieldfiliere1.getText();
        String promo = jTextFieldpromo.getText();
        
        Homebean1 homebean = new Homebean1(0,nom_prof,cours,salle,jour,filiere,metier,promo);
       
        Homebal homeobj = new Homebal();
        homeobj.insert1(homebean);
        loadTable1();
        clearTextFieldData();
    }//GEN-LAST:event_jButtoniActionPerformed

    int id = 0;

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(null, "Selection un element de la table a suprimmer ou modifier");
        
        }else{
        id = (int) jTable1.getValueAt(row, 0);
        Homebal bal = new Homebal();
        Homebean1 bean = bal.returnAllDataToTextField1(id);
        jTextFieldnom_p.setText(bean.getNom_prof());
        jTextFieldcours.setText(bean.getCours());
        jComboBoxsalle.setSelectedItem(bean.getSalle());
        jTextFielddate.setText(bean.getJour());
        jTextFieldmetier1.setText(bean.getMetier());
        jTextFieldfiliere1.setText(bean.getFiliere());
        jTextFieldpromo.setText(bean.getPromo());
        
                
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmActionPerformed
        // TODO add your handling code here:
        String nom_prof = jTextFieldnom_p.getText();
        String cours = jTextFieldcours.getText();
        String salle = (String)jComboBoxsalle.getSelectedItem();
        String jour = jTextFielddate.getText();
        String metier = jTextFieldmetier1.getText();
        String filiere = jTextFieldfiliere1.getText();
        String promo = jTextFieldpromo.getText();
        
        Homebean1 homebean1 = new Homebean1(id,nom_prof,cours,salle,jour,filiere,metier,promo);
        
        Homebal bal = new Homebal();
        
        bal.updateData1(homebean1);
        
        loadTable1();
        //clearTextFieldData();
    }//GEN-LAST:event_jButtonmActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Homeframe homeobj = new Homeframe();
        homeobj.show();
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsActionPerformed
        // TODO add your handling code here:
        Homebal bal = new Homebal();
        bal.deleteRecord1(id);
        loadTable1();
        //clearTextFieldData();
    }//GEN-LAST:event_jButtonsActionPerformed

    private void jButtoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoneActionPerformed
        // TODO add your handling code here:
        clearTextFieldData();
    }//GEN-LAST:event_jButtoneActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        acceuilframe accobj = new acceuilframe();
        accobj.show();
        this.hide();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homeframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homeframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homeframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homeframe1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homeframe1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtone;
    private javax.swing.JButton jButtoni;
    private javax.swing.JButton jButtonm;
    private javax.swing.JButton jButtons;
    private javax.swing.JComboBox<String> jComboBoxsalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldcours;
    private javax.swing.JTextField jTextFielddate;
    private javax.swing.JTextField jTextFieldfiliere1;
    private javax.swing.JTextField jTextFieldmetier1;
    private javax.swing.JTextField jTextFieldnom_p;
    private javax.swing.JTextField jTextFieldpromo;
    // End of variables declaration//GEN-END:variables
}
